# syntax=docker/dockerfile:1
# vim: set syntax=dockerfile:

FROM rhlobo/python3-minimal-base


# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>


WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

CMD [ "python3", "app.py" ]